### ISSUE TITLE
cannot load such file -- google/api/annotations_pb

### ISSUE THREAD

**Issue by taflahi** [mia-0032/fluent-plugin-gcloud-pubsub-custom#50]
Hello,

I am trying to use this plugin but get some error like this:

>/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- google/rpc/status_pb (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/grpc-1.6.6-x86_64-linux/src/ruby/lib/grpc/google_rpc_status_utils.rb:16:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-gax-0.8.12/lib/google/gax/grpc.rb:31:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-gax-0.8.12/lib/google/gax/errors.rb:32:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-gax-0.8.12/lib/google/gax/api_callable.rb:32:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-gax-0.8.12/lib/google/gax.rb:30:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/v1/publisher_client.rb:28:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/v1.rb:16:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/service.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/project.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-gcloud-pubsub-custom-1.0.2/lib/fluent/plugin/gcloud_pubsub/client.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-gcloud-pubsub-custom-1.0.2/lib/fluent/plugin/out_gcloud_pubsub.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:102:in `block in search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:99:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:99:in `search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:44:in `lookup'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin.rb:146:in `new_impl'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin.rb:104:in `new_output'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:128:in `add_match'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:72:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:64:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:64:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/root_agent.rb:112:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/engine.rb:131:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/engine.rb:96:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:770:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:553:in `dry_run'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:571:in `supervise'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:476:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:23:in `load'
	from /usr/local/bin/fluentd:23:in `<main>'

That was happened when I used google-gax v 0.8.12

When I downgrade the version to 0.8.10, I got a different error like this:
>/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- google/api/annotations_pb (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/pubsub/v1/pubsub_pb.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/v1/publisher_client.rb:31:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/v1.rb:16:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/service.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub/project.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-pubsub-0.27.1/lib/google/cloud/pubsub.rb:17:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-gcloud-pubsub-custom-1.0.2/lib/fluent/plugin/gcloud_pubsub/client.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-gcloud-pubsub-custom-1.0.2/lib/fluent/plugin/out_gcloud_pubsub.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:102:in `block in search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:99:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:99:in `search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/registry.rb:44:in `lookup'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin.rb:146:in `new_impl'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/plugin.rb:104:in `new_output'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:128:in `add_match'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:72:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:64:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/agent.rb:64:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/root_agent.rb:112:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/engine.rb:131:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/engine.rb:96:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:770:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:553:in `dry_run'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:571:in `supervise'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/supervisor.rb:476:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.21/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:23:in `load'
	from /usr/local/bin/fluentd:23:in `<main>'

I am using fluentd v 0.14.21, fluent-plugin-gcloud-pubsub-custom v 1.0.2

What do you think what I am missing?

I am installing all of this on ubuntu 16.04

**Comment by taflahi** [comment]
It seems like only a permission issue

Thanks anyway
