### ISSUE TITLE
[ERROR] User not authorized to perform this action

### ISSUE THREAD

**Issue by annony-zx** [mia-0032/fluent-plugin-gcloud-pubsub-custom#62]
Hi all,
I want pull message from a topic in pub/sub use Fluent instead of Logstash, but always meet error both `td-agent v3` and FluentD install via Gem `(Ruby 2.7, FluentD 1.10.3)`.

Anyone you help me with this problem ?

**Notes:** I used this key with Logstash it run normaly :(

- This is my config:
```bash
<source>
  @type gcloud_pubsub
  tag gcp.pull
  project <my_project_id>
  key <path_to_my_json_key>
  topic projects/<my_project_name>/topics/<my_topic_name>
  subscription projects/<my_project_name>/subscriptions/<my_subscription_name>
  max_messages 1000
  return_immediately false
  pull_interval 0.5
  pull_threads 2
  parse_error_action exception
  enable_rpc false
  <parse>
    @type json
  </parse>
</source>

<match gcp.pull>
  @type copy
  <store>
    @type file
    path /tmp/demo-pubsub-%Y%m%d
    append true
    <buffer>
      @type memory
      flush_mode interval
      flush_interval 10s
    </buffer>
    <format>
      @type json
    </format>
  </store>
</match>

```
- This is my error log:
```bash
2020-05-03 23:48:16 +0700 [error]: #0 unexpected error error_class=Google::Cloud::PermissionDeniedError error="7:User not authorized to perform this action."
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/google-cloud-pubsub-0.30.2/lib/google/cloud/pubsub/service.rb:459:in `rescue in execute'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/google-cloud-pubsub-0.30.2/lib/google/cloud/pubsub/service.rb:455:in `execute'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/google-cloud-pubsub-0.30.2/lib/google/cloud/pubsub/service.rb:99:in `get_topic'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/google-cloud-pubsub-0.30.2/lib/google/cloud/pubsub/project.rb:154:in `topic'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluent-plugin-gcloud-pubsub-custom-1.3.2/lib/fluent/plugin/gcloud_pubsub/client.rb:65:in `initialize'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluent-plugin-gcloud-pubsub-custom-1.3.2/lib/fluent/plugin/in_gcloud_pubsub.rb:123:in `new'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluent-plugin-gcloud-pubsub-custom-1.3.2/lib/fluent/plugin/in_gcloud_pubsub.rb:123:in `start'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/root_agent.rb:200:in `block in start'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/root_agent.rb:188:in `each'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/root_agent.rb:175:in `each'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/root_agent.rb:175:in `lifecycle'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/root_agent.rb:199:in `start'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/engine.rb:248:in `start'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/engine.rb:147:in `run'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/supervisor.rb:600:in `block in run_worker'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/supervisor.rb:837:in `main_process'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/supervisor.rb:594:in `run_worker'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/lib/fluent/command/fluentd.rb:350:in `<top (required)>'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/gems/fluentd-1.10.3/bin/fluentd:8:in `<top (required)>'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/bin/fluentd:23:in `load'
  2020-05-03 23:48:16 +0700 [error]: #0 /usr/local/rvm/gems/ruby-2.7.0/bin/fluentd:23:in `<main>'
2020-05-03 23:48:16 +0700 [error]: #0 unexpected error error_class=Google::Cloud::PermissionDeniedError error="7:User not authorized to perform this action."
```

**Comment by annony-zx** [comment]
Sory , I closed issue because i miss View Roles.
