### ISSUE TITLE
d

### ISSUE THREAD

**Issue by mslagle** [mia-0032/fluent-plugin-gcloud-pubsub-custom#80]
After following the readme, I am getting the following error, causing multiple pod restarts.

unexpected error error_class=TypeError error="no implicit conversion of nil into String"

Full stacktrace:
```
[info]: #0 starting fluentd worker pid=24 ppid=1 worker=0
[error]: #0 unexpected error error_class=TypeError error="no implicit conversion of nil into String"
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/googleauth-1.1.2/lib/googleauth/credentials.rb:515:in 'initialize'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/googleauth-1.1.2/lib/googleauth/credentials.rb:515:in 'new'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/googleauth-1.1.2/lib/googleauth/credentials.rb:515:in 'client_options'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/googleauth-1.1.2/lib/googleauth/credentials.rb:485:in 'init_client'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/googleauth-1.1.2/lib/googleauth/credentials.rb:542:in 'update_from_filepath'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/googleauth-1.1.2/lib/googleauth/credentials.rb:363:in 'initialize'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/google-cloud-pubsub-2.3.2/lib/google/cloud/pubsub.rb:102:in 'new'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/google-cloud-pubsub-2.3.2/lib/google/cloud/pubsub.rb:102:in 'new'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluent-plugin-gcloud-pubsub-custom-1.6.0/lib/fluent/plugin/gcloud_pubsub/client.rb:66:in 'initialize'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluent-plugin-gcloud-pubsub-custom-1.6.0/lib/fluent/plugin/in_gcloud_pubsub.rb:133:in 'new'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluent-plugin-gcloud-pubsub-custom-1.6.0/lib/fluent/plugin/in_gcloud_pubsub.rb:133:in 'start'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:203:in 'block in start'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:192:in 'block (2 levels) in lifecycle'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:191:in 'each'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:191:in 'block in lifecycle'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:178:in 'each'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:178:in 'lifecycle'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:202:in 'start'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/engine.rb:248:in 'start'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/engine.rb:147:in 'run'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:717:in 'block in run_worker'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:968:in 'main_process'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:708:in 'run_worker'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:372:in '<top (required)>'
[error]: #0 /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in 'require'
[error]: #0 /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in 'require'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/fluentd-1.14.5/bin/fluentd:15:in '<top (required)>'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/bin/fluentd:23:in 'load'
[error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/bin/fluentd:23:in '<main>'
```

This block is causing an issue
```
<source>
        @type gcloud_pubsub
        tag [tag name]
        project [gcp project id]
        topic [topic name]
        key "#{ENV['GOOGLE_APPLICATION_CREDENTIALS']}"
        subscription "#{ENV['SUBSCRIPTION_NAME']}"
        parse_error_action warning
        format json
</source>
```

This is the only source in my configuration.  I have tried adding/removing parameters without getting this to work.

**Comment by mslagle** [comment]
After following the stacktrace, I discovered I had a malformed service account json file.  I was using an integration to inject it and it was injected wrongly.  After fixing the injection, the plugin began working correctly.

**Comment by mia-0032** [comment]
Thanks for your reporting. I'll close this issue.
